services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5434:5432"

  migrations:
    build: .
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    command: >
      sh -c "
        goose -dir db/migrations postgres \"user=$$DB_USER dbname=$$DB_NAME password=$$DB_PASSWORD host=$$DB_HOST port=$$DB_PORT sslmode=disable\" up
      "
    profiles: [ "migrate" ]

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - APP_PORT=8080
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
